// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnlxsgtkrpgelrcplzin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubHhzZ3RrcnBnZWxyY3BsemluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzAxOTYsImV4cCI6MjA2NDUwNjE5Nn0.xvyXeYOXy4o8-A1GgwszaNBgYN3AjEtFmBQRY3PyiLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);